version: '3.6'
name: music_app-local
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 初始化数据库(后续的初始化sql会在这个库执行)
      MYSQL_DATABASE: music
      # root 密码
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "13306:3306"
    volumes:
      # 数据挂载
      - ./mysql/data/:/var/lib/mysql/
      # 配置挂载
      - ./mysql/conf/:/etc/mysql/conf.d/
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true

  redis:
    image: redis:6.2.7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - ./redis/conf:/redis/config:rw
      # 数据文件
      - ./redis/data/:/redis/data/:rw
    command: "redis-server /redis/config/redis.conf"
    privileged: true

  nginx-web:
    image: nginx:1.22.1
    container_name: nginx-web
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "1880:80"
      - "1443:443"
    volumes:
      # 证书映射
      - ./nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - ./nginx/html:/usr/share/nginx/html
      # 日志目录
      - ./nginx/log:/var/log/nginx
    privileged: true

  music-server:
    image: music-server:0.8.3
    container_name: music-server1
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      # 配置文件
      - ./server/log1/music/server1/logs/:/root/logs/musicWebsite
      - ./../data/:/data/music
    privileged: true

  music-server-node-0:
    image: music-server:0.8.3
    container_name: music-server2
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    volumes:
      # 配置文件
      - ./server/log2/music/server1/logs/:/root/logs/musicWebsite
      - ./../data/:/data/music
    privileged: true